import type { Metadata } from "next";
import "./globals.css";
import SmoothScrollProvider from "./SmoothScroll";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import Providers from "./NProgress";
import TopBar from "@/components/TopBar";
import { GoogleAnalytics } from '@next/third-parties/google'
import Whatsapp from "@/components/Whatsapp";
import Script from "next/script";

export const metadata: Metadata = {
  title: "StockTech Investment",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="shortcut icon" href="/assets/logo/logo.png" type="image/x-icon" />
        <Script
          src="https://www.googletagmanager.com/gtag/js?id=AW-16919570508"
          strategy="afterInteractive"
        />
        <Script id="google-analytics" strategy="afterInteractive">
          {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', 'AW-16919570508');
          `}
        </Script>
      </head>
      <body>
        <Providers>
          <SmoothScrollProvider>
            <TopBar />
            <Header />
            {children}
            <Whatsapp />
            <Footer />
          </SmoothScrollProvider>
        </Providers>
        <GoogleAnalytics gaId="G-6NG8B6WM57" />
      </body>
    </html>
  );
}
