import type { Metadata } from "next";
import "./globals.css";
import SmoothScrollProvider from "./SmoothScroll";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import Providers from "./NProgress";

export const metadata: Metadata = {
  title: "StockTech Investment",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="shortcut icon" href="/assets/logo/logo.png" type="image/x-icon" />
      </head>
      <body>
        <Providers>
          <SmoothScrollProvider>
            <Header />
            {children}
            <Footer />
          </SmoothScrollProvider>
        </Providers>
      </body>
    </html>
  );
}
